### PR TITLE
Include apps in search result

### PR DESCRIPTION
**Pull request by kimdv**

### CODE REVIEW

**Comment by BalestraPatrick** [comment]
@kimdv Seems like the build has failed because the project doesn't compile due to a syntax error.

**Comment by BalestraPatrick** [comment]
Can we maybe have two sections for "Apps" and "Accessories"? In this way it's possible do distinguish them and for the future, it will make it easier to build the advanced search feature.

**Comment by kimdv** [comment]
Strange! 

I have just build the app locally o.O

To separate pages or?
Right now I have accessories first, a grey line and then apps.

**Comment by kimdv** [comment]
We could also add some sort if "tab" under the 'Search result for "Elgato"'

Where users can switch from accessory/app ?

**Comment by BalestraPatrick** [comment]
I just switched to this branch and tried your solution. It's very confusing to have both search at the same time, because if you search a term that's not present in the HomeKit apps, you get the following screen.
screen shot 2018-08-22 at 5 53 40 pm

This is definitely confusing and it doesn't make sense from the UX perspective to have a single search bar and display separate results from the two tables. I think we can leave the search bar uniquely for the accessories (which is what most users will need to do). We can now start implementing an advanced search mode #3 (which is going to be a separate page) where users can decide to search an accessory, manufacturer or iOS HomeKit app. What do you think? We can close this PR for now since we're going to embed this into a separate feature.

**Comment by kimdv** [comment]
Let’s make the advanced search !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
