### PR TITLE
Update to Swift 5

### PR DESCRIPTION
**Pull request by kimdv**

### CODE REVIEW

**Comment by BalestraPatrick** [comment]
Mmh, looks like CI failed on that. Is it required to move to Swift 5 right now? We could also encounter some problems when deploying to Heroku since we would have to find a suitable Swift 5 Linux version and hope it works there too.

**Comment by kimdv** [comment]
Not other than Swift 5 performs a lot better than Swift 4.1 🤷‍♂️
Specially when coming to string. I think I rad somewhere that swift.org loads 20% faster or something like that, when they moved from Swift 4.2 to Swift 5. 

Can se not just use the plan Swift 5 image? (Never used Heroku and Swift before)

**Comment by BalestraPatrick** [comment]
We have specified to use the latest Docker image in the circle configuration but unfortunately it's not doing so. https://github.com/BalestraPatrick/HomeKitty/blob/b905b2a5c9f786b65f60fc59ce0a0301c377af95/circle.yml#L6

**Comment by kimdv** [comment]
Maybe we should try and pin to version `5.0.1`

**Pull request closed without merging**
